matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_4_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT_29/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_4_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT_29/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_1_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT5_29/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_1_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT5_29/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_2_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT8_29/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_2_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT8_29/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_3_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT11_29/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_3_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT11_29/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_8_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT_34/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_8_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT_34/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_5_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT5_34/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_5_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT5_34/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_6_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT8_34/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_6_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT8_34/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_7_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT11_34/dkaiA_wt.txt'); run('Plot_rawLuminescence.m')"
matlab -nodisplay -batch "assignin('base', 'fileName', 'Exp03Resetting/output_file_7_20250726.csv'); assignin('base', 'paramfileName', 'Exp03Resetting/ZT11_34/dkaiA_148L156A.txt'); run('Plot_rawLuminescence.m')"
 
