function PRC_plot(plotDefs, strainStyles, cfg)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PRC_plot   Phase Response Curve engine — called from PRC_config.m
%
% Do not edit this file to change data or plots.
% All experiment definitions live in PRC_config.m.
%
% INPUTS
% ------
%   plotDefs     — struct array, one element per figure/tile-set.
%                  Each element has fields:
%                    .outputName  — output file prefix (string)
%                    .title       — overall figure title (string)
%                    .nCols       — number of tile columns (integer)
%                    .tileTitles  — cell array of per-tile title strings
%                    .tiles       — cell array of tile condition arrays.
%                                  Each condition has fields:
%                                    strain, temp, zt_pulse,
%                                    ref_file, pulse_file, color
%   strainStyles — struct with one field per strain key. Each field has:
%                    .displayName, .marker, .lineStyle
%                  (colors come from the per-condition .color field)
%   cfg          — figure settings struct with fields:
%                    .tileWidth, .tileHeight  — inches per tile
%                    .hGap, .vGap            — inter-tile gaps (inches)
%                    .marginL/R/T/B          — outer margins (inches)
%                    .tickFontSize, .legendFontSize, .axLabelSize
%                    .lineWidth    — connecting line width   (default 2.5)
%                    .markerSize   — marker size             (default 9)
%                    .capSize      — error bar cap size      (default 8)
%                    .ebLineWidth  — error bar line width    (default 2.0)
%
% PHASE-SHIFT CONVENTION
% ----------------------
%   ΔΦ = mean(reference) − mean(pulsed)
%   Positive → phase advance;   Negative → phase delay.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Safety-net defaults for line/marker/cap settings
% (overridden by values set in PRC_config.m)
if ~isfield(cfg,'lineWidth'),   cfg.lineWidth   = 2.5; end
if ~isfield(cfg,'markerSize'),  cfg.markerSize  = 9;   end
if ~isfield(cfg,'capSize'),     cfg.capSize     = 8;   end
if ~isfield(cfg,'ebLineWidth'), cfg.ebLineWidth = 2.0; end

for p = 1:numel(plotDefs)
    pd = plotDefs(p);
    fprintf('\n=== Plot %d / %d : %s ===\n', p, numel(plotDefs), pd.outputName);
    buildPRCFigure(pd, strainStyles, cfg);
end

end % PRC_plot

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% -- buildPRCFigure : render one tiled figure ----------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function buildPRCFigure(pd, strainStyles, cfg)

nTiles = numel(pd.tiles);
nCols  = pd.nCols;
nRows  = ceil(nTiles / nCols);

tW   = cfg.tileWidth;
tH   = cfg.tileHeight;
figW = cfg.marginL + nCols*tW + (nCols-1)*cfg.hGap + cfg.marginR;
figH = cfg.marginB + nRows*tH + (nRows-1)*cfg.vGap + cfg.marginT;

fig = figure('Units','inches','Position',[1.5, 1.5, figW, figH]);

% Pre-compute phase shifts for all tiles
tileData  = cell(1, nTiles);
allShifts = [];
allZT     = [];
for t = 1:nTiles
    tileData{t} = computePhaseShifts(pd.tiles{t});
    sKeys = keys(tileData{t});
    for k = 1:numel(sKeys)
        s = tileData{t}(sKeys{k});
        allShifts = [allShifts; s.dphi + s.sem; s.dphi - s.sem]; %#ok
        allZT     = [allZT; s.zt]; %#ok
    end
end

% Shared symmetric y-range across all tiles
yRange = max(abs(allShifts)) * 1.3;
if isempty(yRange) || yRange == 0, yRange = 1; end

% Shared x-axis limits
xLims = [min(allZT)-1, max(allZT)+1];

% Draw tiles
for t = 1:nTiles
    row = ceil(t / nCols);
    col = mod(t-1, nCols) + 1;

    xL = (cfg.marginL + (col-1)*(tW + cfg.hGap)) / figW;
    yB = (cfg.marginB + (nRows-row)*(tH + cfg.vGap)) / figH;
    wN = tW / figW;
    hN = tH / figH;

    ax = axes('Units','normalized','Position',[xL, yB, wN, hN]); %#ok
    drawTile(ax, tileData{t}, pd.tiles{t}, strainStyles, xLims, yRange, cfg);

    % Axis labels on edge tiles only
    if row == nRows
        xlabel(ax, 'ZT of Dark Pulse (h)', 'FontSize', cfg.axLabelSize);
    else
        set(ax, 'XTickLabel', []);
    end
    if col == 1
        ylabel(ax, '\Delta\Phi (h)', 'FontSize', cfg.axLabelSize);
    else
        set(ax, 'YTickLabel', []);
    end

    % Per-tile title
    if isfield(pd, 'tileTitles') && t <= numel(pd.tileTitles)
        title(ax, pd.tileTitles{t}, 'FontSize', 12, 'FontWeight', 'bold', ...
            'Interpreter', 'tex');
    end
end

% Overall figure title
if ~isempty(pd.title)
    annotation(fig, 'textbox', [0, 1-cfg.marginT/figH, 1, cfg.marginT/figH], ...
        'String', pd.title, ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'FontSize', 15, 'FontWeight', 'bold', ...
        'EdgeColor', 'none', 'Interpreter', 'tex');
end

% Save
fig.PaperUnits    = 'inches';
fig.PaperSize     = [figW, figH];
fig.PaperPosition = [0, 0, figW, figH];
exportgraphics(fig, pd.outputName, 'ContentType', 'vector');
% print(fig, pd.outputName, '-dpng', '-r300');
fprintf('   Saved: %s', pd.outputName, pd.outputName);

end % buildPRCFigure

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% -- drawTile : draw one PRC axes ----------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function drawTile(ax, seriesMap, conditions, strainStyles, xLims, yRange, cfg)
% Each series is one {strain, temp} combination.
% Individual ZT points each have their own color from colorMap.
% The connecting line is drawn first (below markers).

hold(ax, 'on');


% sKeys = keys(seriesMap);

% Preserve insertion order from conditions array
sKeys = {};
for i = 1:numel(conditions)
    key = [conditions(i).strain '__' strrep(conditions(i).temp, ' ', '_')];
    if ~ismember(key, sKeys)
        sKeys{end+1} = key;
    end
end


% Collect legend entries: one per strain (not per ZT point)
legendHandles = gobjects(numel(sKeys), 1);
legendLabels  = cell(numel(sKeys), 1);

for k = 1:numel(sKeys)
    s  = seriesMap(sKeys{k});
    st = strainStyles.(s.strain);

    [~, idx] = sort(s.zt);
    zt_s   = s.zt(idx);
    dphi_s = s.dphi(idx);
    sem_s  = s.sem(idx);
    cols   = s.colors(idx);

    % Connecting line — blended color, drawn first so markers sit on top
    lineCol = (cols{1} + cols{end}) / 2;
    plot(ax, zt_s, dphi_s, ...
        'Color',     lineCol, ...
        'LineStyle', st.lineStyle, ...
        'LineWidth', cfg.lineWidth, ...          % <-- cfg controlled
        'HandleVisibility', 'off');

    % Per-ZT error bars and markers
    for j = 1:numel(zt_s)
        h = errorbar(ax, zt_s(j), dphi_s(j), sem_s(j), ...
            'Color',          cols{j}, ...
            'LineStyle',      'none', ...
            'LineWidth',      cfg.ebLineWidth, ...   % <-- cfg controlled
            'Marker',         st.marker, ...
            'MarkerSize',     cfg.markerSize, ...    % <-- cfg controlled
            'MarkerFaceColor',cols{j}, ...
            'CapSize',        cfg.capSize, ...       % <-- cfg controlled
            'HandleVisibility', 'off');
        if j == 1
            % Register first point as legend proxy for this strain
            set(h, 'HandleVisibility', 'on', ...
                'Color', lineCol, 'MarkerFaceColor', lineCol);
            legendHandles(k) = h;
            legendLabels{k}  = sprintf('%s  %s', st.displayName, s.temp);
            % Restore actual color
            set(h, 'Color', cols{j}, 'MarkerFaceColor', cols{j});
        end
    end
end

% Zero line
plot(ax, xLims, [0 0], 'k--', 'LineWidth', 1.2, 'HandleVisibility', 'off');

% Axes formatting
grid(ax, 'on'); box(ax, 'off');
ax.XGrid = 'on'; ax.YGrid = 'off'; ax.XMinorGrid = 'off';
ax.GridColor     = [0 0 0];
ax.GridLineStyle = ':';
ax.GridAlpha     = 0.5;
ax.FontSize      = cfg.tickFontSize;
set(ax, 'LineWidth', 1.5, 'TickDir', 'out');
xlim(ax, xLims);
ylim(ax, [-yRange, yRange]);
ax.XTick = 0:2:24;

% Advance / Delay labels (positive = advance, negative = delay)
text(ax, xLims(1)+0.15,  yRange*0.88, '▲ Advance', ...
    'FontSize', 15, 'Color', [0.5 0.5 0.5], 'VerticalAlignment', 'top');
text(ax, xLims(1)+0.15, -yRange*0.88, '▼ Delay', ...
    'FontSize', 15, 'Color', [0.5 0.5 0.5], 'VerticalAlignment', 'bottom');

% Legend
lgd = legend(ax, legendHandles, legendLabels, ...
    'Location',   'best', ...
    'FontSize',   cfg.legendFontSize, ...
    'Interpreter','tex', ...
    'Box',        'on', ...
    'EdgeColor',  [0.4 0.4 0.4]);
lgd.ItemTokenSize(2) = 2;

hold(ax, 'off');

end 
% drawTile

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% -- computePhaseShifts : build seriesMap for one tile -------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function seriesMap = computePhaseShifts(conditions)
% Groups conditions by {strain, temp}.
% Each series accumulates ZT points with individual per-ZT colors.
%
% SIGN CONVENTION:
%   ΔΦ = mean(reference) − mean(pulsed)
%   Positive → advance;   Negative → delay.

seriesMap = containers.Map('KeyType','char','ValueType','any');

for i = 1:numel(conditions)
    d = conditions(i);
    if isempty(d.pulse_file)
        fprintf('   ZT%d  %s  %s — skipped\n', d.zt_pulse, d.strain, d.temp);
        continue;
    end

    ref_phases   = readPhases(d.ref_file);
    pulse_phases = readPhases(d.pulse_file);

    ref_mean   = mean(ref_phases,   'omitnan');
    pulse_mean = mean(pulse_phases, 'omitnan');
    ref_n      = sum(~isnan(ref_phases));
    pulse_n    = sum(~isnan(pulse_phases));
    ref_sem    = std(ref_phases,   'omitnan') / sqrt(ref_n);
    pulse_sem  = std(pulse_phases, 'omitnan') / sqrt(pulse_n);

    delta_phi = ref_mean - pulse_mean;   % positive = advance
    delta_sem = sqrt(ref_sem^2 + pulse_sem^2);

    fprintf('   ZT%2d  %-22s  %s  ->  ΔΦ = %+.3f h\n', ...
        d.zt_pulse, d.strain, d.temp, delta_phi);

    key = [d.strain '__' strrep(d.temp, ' ', '_')];
    if isKey(seriesMap, key)
        s = seriesMap(key);
    else
        s.strain = d.strain;
        s.temp   = d.temp;
        s.zt     = [];
        s.dphi   = [];
        s.sem    = [];
        s.colors = {};
    end
    s.zt     = [s.zt;   d.zt_pulse];
    s.dphi   = [s.dphi; delta_phi];
    s.sem    = [s.sem;  delta_sem];
    s.colors = [s.colors; {d.color}];
    seriesMap(key) = s;
end

end % computePhaseShifts

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% -- readPhases --
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function phases = readPhases(filepath)
% Return numeric phases (column 2) from a two-column CSV; skip header.
t      = readtable(filepath, 'ReadVariableNames', true, ...
                             'VariableNamingRule', 'preserve');
phases = t{:, 2};
end
